<a href="https://colab.research.google.com/github/evgenia-18/ICS-493633/blob/main/%D0%9B%D0%B0%D0%B11_%D0%93%D0%BB%D1%83%D1%88%D0%B0%D0%BA_%D0%84%D0%B2%D0%B3%D0%B5%D0%BD%D1%96%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Була присутня на парі

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [4]:
a = np.random.randint(1, 6, size=(3, 3))
a

array([[2, 3, 2],
       [4, 3, 1],
       [5, 2, 3]])

In [5]:
det = np.linalg.det(a)
det

np.float64(-21.0)

In [6]:
product = np.prod(a)
product

np.int64(4320)

In [7]:
prod_1 = np.prod(a[0])
prod_2 = np.prod(a[1])
prod_3 = np.prod(a[2])
prod_1*prod_2*prod_3

np.int64(4320)

In [8]:
np.sum(a)

np.int64(25)

In [9]:
np.max(a)

np.int64(5)

In [10]:
np.min(a)

np.int64(1)

In [11]:
np.mean(a)

np.float64(2.7777777777777777)

In [12]:
sqrt_a = np.sqrt(a)

print("Матриця квадратних коренів:")
print(sqrt_a)


Матриця квадратних коренів:
[[1.41421356 1.73205081 1.41421356]
 [2.         1.73205081 1.        ]
 [2.23606798 1.41421356 1.73205081]]


In [14]:
row_sums = np.sum(a, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")
print(row_sums)


Сума елементів кожного рядка:
[[ 7]
 [ 8]
 [10]]


In [15]:
a.sum(axis=1).reshape(-1, 1)

array([[ 7],
       [ 8],
       [10]])

In [17]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [18]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [19]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

In [20]:
vector = np.random.randint(0, 10, size=25)
vector

array([4, 1, 0, 1, 2, 1, 7, 4, 2, 4, 0, 9, 4, 7, 4, 5, 3, 9, 5, 8, 3, 5,
       2, 8, 8])

In [21]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 8, 8, 8, 7, 7, 5, 5, 5, 4, 4, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1,
       1, 0, 0])

In [36]:
from scipy import stats
mode = stats.mode(vector)
medina = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)

print("Мода:", mode )
print("Медіана:", np.median)
print("Середнє:", mean )
print("Максимальне значення:", max_value )
print("Мінімальне значення:", min_value )

Мода: ModeResult(mode=np.int64(4), count=np.int64(5))
Медіана: <function median at 0x7e9933ff1ee0>
Середнє: 4.24
Максимальне значення: 9
Мінімальне значення: 0


In [25]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)


Матриця 1:
[[10  3  3  4]
 [ 3  2  1  4]
 [ 3  6  7  6]
 [ 3  3  6  3]]
Матриця 2:
[[10  5  7  7]
 [10  3  5  7]
 [ 1  9  6  8]
 [ 2  7 10  9]]


In [35]:
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_division)



Сума матриць:
[[20  8 10 11]
 [13  5  6 11]
 [ 4 15 13 14]
 [ 5 10 16 12]]

Різниця матриць:
[[ 0 -2 -4 -3]
 [-7 -1 -4 -3]
 [ 2 -3  1 -2]
 [ 1 -4 -4 -6]]

Поелементний добуток матриць:
[[1.         0.6        0.42857143 0.57142857]
 [0.3        0.66666667 0.2        0.57142857]
 [3.         0.66666667 1.16666667 0.75      ]
 [1.5        0.42857143 0.6        0.33333333]]


In [27]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [28]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [29]:
x2 = np.arange(3.)
x2

array([0., 1., 2.])

In [30]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [37]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [38]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [39]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

2 частина

In [40]:
vector = np.array([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

In [41]:
v1 = np.matrix([1, 2, 3, 4, 5])
v1

matrix([[1, 2, 3, 4, 5]])

In [42]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [43]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [44]:
v[::-1]

array([5, 4, 3, 2, 1])

In [45]:
v = np.flip(v)
v

array([5, 4, 3, 2, 1])

In [46]:
np.mean(v)

np.float64(3.0)

In [47]:
np.max(v)

np.int64(5)

In [48]:
np.min(v)

np.int64(1)

In [51]:
v1 = np.array([1, 2, 3])
v2 = np.array([5, 6, 4])

In [52]:
v1

array([1, 2, 3])

In [53]:
v2

array([5, 6, 4])

In [54]:
np.dot(v1, v2)

np.int64(29)

In [55]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [57]:
v1 = np.array([1, 0, 1])
v2 = np.array([0, 1, 0])

np.dot(v1, v2)

np.int64(0)

In [58]:
v = np.array([1, 2, 3, 2, 4, 5, 3])

np.unique(v)

array([1, 2, 3, 4, 5])

In [59]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1-v2)
print(v2-v1)
print(v1+v2)
print(v1*v2)
print(v2*v1)
print(v1/v2)
print(v2/v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


In [60]:
vector = np.array([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
length

np.float64(7.416198487095663)

In [61]:
np.isclose(length, 5)

np.False_

In [62]:
a = np.random.randint(0, 11, (3, 3))
a

array([[ 7, 10,  1],
       [ 1,  6,  6],
       [ 2,  0,  1]])

In [63]:
np.linalg.det(a)

np.float64(139.99999999999994)

In [64]:
np.linalg.inv(a)

array([[ 0.04285714, -0.07142857,  0.38571429],
       [ 0.07857143,  0.03571429, -0.29285714],
       [-0.08571429,  0.14285714,  0.22857143]])

In [65]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b = np.array([5, 3, 4])

x = np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [0.4 1.8 0.2]
Матричний метод [0.4 1.8 0.2]


In [67]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [68]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [69]:
matrix = np.matrix([[2, 2, 2],[2, 2, 2],[2, 2, 2]])
np.allclose(matrix, matrix.T)

True

In [70]:
np.trace(matrix)

np.int64(6)

In [71]:
b = np.matrix([[5, 3, 4],[2, 3, 5],[3, 2, 3]])

print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]
